### ISSUE TITLE
[2004dj] redshift correction

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/sne-external-spectra#8]
sne-external-spectra/Suspect/II_spec_ascii_20110715/2004dj/

This and others need a redshift correction.

I will fix, push, and close.

**Comment by guillochon** [comment]
@jparrent Is this event all properly corrected now?

**Comment by jparrent** [comment]
@guillochon The data for this event have been updated properly in the SuSpect directory, but the plot still appears with the old numbers for some reason. 

I'll close this and other issues when I see the fix come through. I have in mind to keep all of this tidier as well.

**Comment by guillochon** [comment]
Great, I hadn't rerun the import script recently so these changes haven't
yet appeared online, but will soon.

On Tuesday, February 9, 2016, J. Parrent <notifications@github.com> wrote:

> @guillochon <https://github.com/guillochon> The data for this event have
> been updated properly in the SuSpect directory, but the plot still appears
> with the old numbers for some reason.
>
> I'll close this and other issues when I see the fix come through. I have
> in mind to keep all of this tidier as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astrotransients/sne-external-spectra/issues/8#issuecomment-182050259>
> .
>


-- 
James Guillochon
Einstein Fellow at the Harvard-Smithsonian CfA
jguillochon@cfa.harvard.edu

**Comment by jparrent** [comment]
Fixed.
